### ISSUE TITLE
gofile  upload failed 

### ISSUE THREAD

**Issue by NEWBIENOOB-0** [Alyetama/Gofile#7]
Traceback (most recent call last):
  File "/home/edith/.local/bin/gofile", line 8, in <module>
    sys.exit(gofile.main())
  File "/home/edith/.local/lib/python3.10/site-packages/gofilepy/gofile.py", line 177, in main
    gofile_upload(
  File "/home/edith/.local/lib/python3.10/site-packages/gofilepy/gofile.py", line 62, in gofile_upload
    best_server = get_server.json()['data']['server']
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Alyetama** [comment]
Thank you for reporting the issue. The issue was fixed in the latest release. Please update the package and try again!​
```
pip install -U gofilepy
```
